### PR TITLE
Fixes Google Tests

### PR DESCRIPTION
**Pull request by andrefreitas**
Fixes Google tests errors: https://gist.github.com/andrefreitas/307bd0397a3cb13a601e

I fixed the “assert called with” call and some typos.

### CODE REVIEW

**Comment by andrefreitas** [comment]
@paulproteus can you please review this?

**Comment by paulproteus** [comment]
Ooh, okay. Will look shortly.​

**Comment by andrefreitas** [comment]
I am closing this PR.

**Comment by paulproteus** [comment]
Thanks for your work on it and I'm sorry I wasn't able to comment in a timely fashion.

**Pull request closed without merging**
